export const CHANGE_LANGUAGE_SAGAS: string = 'CHANGE_LANGUAGE_SAGA'
export const SET_ON_DATASET_REDUCER: string = 'SET_ON_DATASET_REDUCER'
export const USERS_SCREEN_SAGA: string = 'USERS_SCREEN_SAGA'
export const USERS_DETAILS_SCREEN_SAGA: string = 'USERS_DETAILS_SCREEN_SAGA'
